//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMRCrawlerEntities : DbContext
    {
        public IMRCrawlerEntities()
            : base("name=IMRCrawlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PDFDetail> PDFDetails { get; set; }
        public DbSet<PDFFormat> PDFFormats { get; set; }
        public DbSet<Treatment> Treatments { get; set; }
    }
}
