//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMRWeb.PDFDetailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PDFDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PDFDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TreatmentIDField;
        
        private System.Nullable<System.DateTime> DateAssignedField;
        
        private System.Nullable<System.DateTime> URDenialDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HowIMRDeterminationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicalCaseSummaryField;
        
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMRIssuesRationalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateofLicensureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentsReviewedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueAtDisputeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TreatmentGuidelinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewerQualificationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TreatmentID {
            get {
                return this.TreatmentIDField;
            }
            set {
                if ((this.TreatmentIDField.Equals(value) != true)) {
                    this.TreatmentIDField = value;
                    this.RaisePropertyChanged("TreatmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<System.DateTime> DateAssigned {
            get {
                return this.DateAssignedField;
            }
            set {
                if ((this.DateAssignedField.Equals(value) != true)) {
                    this.DateAssignedField = value;
                    this.RaisePropertyChanged("DateAssigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> URDenialDate {
            get {
                return this.URDenialDateField;
            }
            set {
                if ((this.URDenialDateField.Equals(value) != true)) {
                    this.URDenialDateField = value;
                    this.RaisePropertyChanged("URDenialDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HowIMRDetermination {
            get {
                return this.HowIMRDeterminationField;
            }
            set {
                if ((object.ReferenceEquals(this.HowIMRDeterminationField, value) != true)) {
                    this.HowIMRDeterminationField = value;
                    this.RaisePropertyChanged("HowIMRDetermination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ClinicalCaseSummary {
            get {
                return this.ClinicalCaseSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicalCaseSummaryField, value) != true)) {
                    this.ClinicalCaseSummaryField = value;
                    this.RaisePropertyChanged("ClinicalCaseSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Diagnosis {
            get {
                return this.DiagnosisField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosisField, value) != true)) {
                    this.DiagnosisField = value;
                    this.RaisePropertyChanged("Diagnosis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string IMRIssuesRationales {
            get {
                return this.IMRIssuesRationalesField;
            }
            set {
                if ((object.ReferenceEquals(this.IMRIssuesRationalesField, value) != true)) {
                    this.IMRIssuesRationalesField = value;
                    this.RaisePropertyChanged("IMRIssuesRationales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string StateofLicensure {
            get {
                return this.StateofLicensureField;
            }
            set {
                if ((object.ReferenceEquals(this.StateofLicensureField, value) != true)) {
                    this.StateofLicensureField = value;
                    this.RaisePropertyChanged("StateofLicensure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Certifications {
            get {
                return this.CertificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificationsField, value) != true)) {
                    this.CertificationsField = value;
                    this.RaisePropertyChanged("Certifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DocumentsReviewed {
            get {
                return this.DocumentsReviewedField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsReviewedField, value) != true)) {
                    this.DocumentsReviewedField = value;
                    this.RaisePropertyChanged("DocumentsReviewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string IssueAtDispute {
            get {
                return this.IssueAtDisputeField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueAtDisputeField, value) != true)) {
                    this.IssueAtDisputeField = value;
                    this.RaisePropertyChanged("IssueAtDispute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TreatmentGuidelines {
            get {
                return this.TreatmentGuidelinesField;
            }
            set {
                if ((object.ReferenceEquals(this.TreatmentGuidelinesField, value) != true)) {
                    this.TreatmentGuidelinesField = value;
                    this.RaisePropertyChanged("TreatmentGuidelines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ReviewerQualifications {
            get {
                return this.ReviewerQualificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewerQualificationsField, value) != true)) {
                    this.ReviewerQualificationsField = value;
                    this.RaisePropertyChanged("ReviewerQualifications");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PDFDetailService.PDFDetailServiceSoap")]
    public interface PDFDetailServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetPDFDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPDFDetails", ReplyAction="*")]
        IMRWeb.PDFDetailService.GetPDFDetailsResponse GetPDFDetails(IMRWeb.PDFDetailService.GetPDFDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPDFDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<IMRWeb.PDFDetailService.GetPDFDetailsResponse> GetPDFDetailsAsync(IMRWeb.PDFDetailService.GetPDFDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPDFDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPDFDetails", Namespace="http://tempuri.org/", Order=0)]
        public IMRWeb.PDFDetailService.GetPDFDetailsRequestBody Body;
        
        public GetPDFDetailsRequest() {
        }
        
        public GetPDFDetailsRequest(IMRWeb.PDFDetailService.GetPDFDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPDFDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int treatmentID;
        
        public GetPDFDetailsRequestBody() {
        }
        
        public GetPDFDetailsRequestBody(int treatmentID) {
            this.treatmentID = treatmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPDFDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPDFDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMRWeb.PDFDetailService.GetPDFDetailsResponseBody Body;
        
        public GetPDFDetailsResponse() {
        }
        
        public GetPDFDetailsResponse(IMRWeb.PDFDetailService.GetPDFDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPDFDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IMRWeb.PDFDetailService.PDFDetail GetPDFDetailsResult;
        
        public GetPDFDetailsResponseBody() {
        }
        
        public GetPDFDetailsResponseBody(IMRWeb.PDFDetailService.PDFDetail GetPDFDetailsResult) {
            this.GetPDFDetailsResult = GetPDFDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PDFDetailServiceSoapChannel : IMRWeb.PDFDetailService.PDFDetailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PDFDetailServiceSoapClient : System.ServiceModel.ClientBase<IMRWeb.PDFDetailService.PDFDetailServiceSoap>, IMRWeb.PDFDetailService.PDFDetailServiceSoap {
        
        public PDFDetailServiceSoapClient() {
        }
        
        public PDFDetailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PDFDetailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDFDetailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDFDetailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMRWeb.PDFDetailService.GetPDFDetailsResponse IMRWeb.PDFDetailService.PDFDetailServiceSoap.GetPDFDetails(IMRWeb.PDFDetailService.GetPDFDetailsRequest request) {
            return base.Channel.GetPDFDetails(request);
        }
        
        public IMRWeb.PDFDetailService.PDFDetail GetPDFDetails(int treatmentID) {
            IMRWeb.PDFDetailService.GetPDFDetailsRequest inValue = new IMRWeb.PDFDetailService.GetPDFDetailsRequest();
            inValue.Body = new IMRWeb.PDFDetailService.GetPDFDetailsRequestBody();
            inValue.Body.treatmentID = treatmentID;
            IMRWeb.PDFDetailService.GetPDFDetailsResponse retVal = ((IMRWeb.PDFDetailService.PDFDetailServiceSoap)(this)).GetPDFDetails(inValue);
            return retVal.Body.GetPDFDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMRWeb.PDFDetailService.GetPDFDetailsResponse> IMRWeb.PDFDetailService.PDFDetailServiceSoap.GetPDFDetailsAsync(IMRWeb.PDFDetailService.GetPDFDetailsRequest request) {
            return base.Channel.GetPDFDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMRWeb.PDFDetailService.GetPDFDetailsResponse> GetPDFDetailsAsync(int treatmentID) {
            IMRWeb.PDFDetailService.GetPDFDetailsRequest inValue = new IMRWeb.PDFDetailService.GetPDFDetailsRequest();
            inValue.Body = new IMRWeb.PDFDetailService.GetPDFDetailsRequestBody();
            inValue.Body.treatmentID = treatmentID;
            return ((IMRWeb.PDFDetailService.PDFDetailServiceSoap)(this)).GetPDFDetailsAsync(inValue);
        }
    }
}
