//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMRWeb.SearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchService.SearchServiceSoap")]
    public interface SearchServiceSoap {
        
        // CODEGEN: Generating message contract since element name searchString from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSimpleSearchResultCount", ReplyAction="*")]
        IMRWeb.SearchService.GetSimpleSearchResultCountResponse GetSimpleSearchResultCount(IMRWeb.SearchService.GetSimpleSearchResultCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSimpleSearchResultCount", ReplyAction="*")]
        System.Threading.Tasks.Task<IMRWeb.SearchService.GetSimpleSearchResultCountResponse> GetSimpleSearchResultCountAsync(IMRWeb.SearchService.GetSimpleSearchResultCountRequest request);
        
        // CODEGEN: Generating message contract since element name searchString from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSimpleSearchResults", ReplyAction="*")]
        IMRWeb.SearchService.GetSimpleSearchResultsResponse GetSimpleSearchResults(IMRWeb.SearchService.GetSimpleSearchResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSimpleSearchResults", ReplyAction="*")]
        System.Threading.Tasks.Task<IMRWeb.SearchService.GetSimpleSearchResultsResponse> GetSimpleSearchResultsAsync(IMRWeb.SearchService.GetSimpleSearchResultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSimpleSearchResultCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSimpleSearchResultCount", Namespace="http://tempuri.org/", Order=0)]
        public IMRWeb.SearchService.GetSimpleSearchResultCountRequestBody Body;
        
        public GetSimpleSearchResultCountRequest() {
        }
        
        public GetSimpleSearchResultCountRequest(IMRWeb.SearchService.GetSimpleSearchResultCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSimpleSearchResultCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool any;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchString;
        
        public GetSimpleSearchResultCountRequestBody() {
        }
        
        public GetSimpleSearchResultCountRequestBody(bool any, string searchString) {
            this.any = any;
            this.searchString = searchString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSimpleSearchResultCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSimpleSearchResultCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMRWeb.SearchService.GetSimpleSearchResultCountResponseBody Body;
        
        public GetSimpleSearchResultCountResponse() {
        }
        
        public GetSimpleSearchResultCountResponse(IMRWeb.SearchService.GetSimpleSearchResultCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSimpleSearchResultCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetSimpleSearchResultCountResult;
        
        public GetSimpleSearchResultCountResponseBody() {
        }
        
        public GetSimpleSearchResultCountResponseBody(int GetSimpleSearchResultCountResult) {
            this.GetSimpleSearchResultCountResult = GetSimpleSearchResultCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSimpleSearchResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSimpleSearchResults", Namespace="http://tempuri.org/", Order=0)]
        public IMRWeb.SearchService.GetSimpleSearchResultsRequestBody Body;
        
        public GetSimpleSearchResultsRequest() {
        }
        
        public GetSimpleSearchResultsRequest(IMRWeb.SearchService.GetSimpleSearchResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSimpleSearchResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool any;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int current;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        public GetSimpleSearchResultsRequestBody() {
        }
        
        public GetSimpleSearchResultsRequestBody(bool any, string searchString, int current, int pageSize) {
            this.any = any;
            this.searchString = searchString;
            this.current = current;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSimpleSearchResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSimpleSearchResultsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMRWeb.SearchService.GetSimpleSearchResultsResponseBody Body;
        
        public GetSimpleSearchResultsResponse() {
        }
        
        public GetSimpleSearchResultsResponse(IMRWeb.SearchService.GetSimpleSearchResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSimpleSearchResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSimpleSearchResultsResult;
        
        public GetSimpleSearchResultsResponseBody() {
        }
        
        public GetSimpleSearchResultsResponseBody(string GetSimpleSearchResultsResult) {
            this.GetSimpleSearchResultsResult = GetSimpleSearchResultsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchServiceSoapChannel : IMRWeb.SearchService.SearchServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceSoapClient : System.ServiceModel.ClientBase<IMRWeb.SearchService.SearchServiceSoap>, IMRWeb.SearchService.SearchServiceSoap {
        
        public SearchServiceSoapClient() {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMRWeb.SearchService.GetSimpleSearchResultCountResponse IMRWeb.SearchService.SearchServiceSoap.GetSimpleSearchResultCount(IMRWeb.SearchService.GetSimpleSearchResultCountRequest request) {
            return base.Channel.GetSimpleSearchResultCount(request);
        }
        
        public int GetSimpleSearchResultCount(bool any, string searchString) {
            IMRWeb.SearchService.GetSimpleSearchResultCountRequest inValue = new IMRWeb.SearchService.GetSimpleSearchResultCountRequest();
            inValue.Body = new IMRWeb.SearchService.GetSimpleSearchResultCountRequestBody();
            inValue.Body.any = any;
            inValue.Body.searchString = searchString;
            IMRWeb.SearchService.GetSimpleSearchResultCountResponse retVal = ((IMRWeb.SearchService.SearchServiceSoap)(this)).GetSimpleSearchResultCount(inValue);
            return retVal.Body.GetSimpleSearchResultCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMRWeb.SearchService.GetSimpleSearchResultCountResponse> IMRWeb.SearchService.SearchServiceSoap.GetSimpleSearchResultCountAsync(IMRWeb.SearchService.GetSimpleSearchResultCountRequest request) {
            return base.Channel.GetSimpleSearchResultCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMRWeb.SearchService.GetSimpleSearchResultCountResponse> GetSimpleSearchResultCountAsync(bool any, string searchString) {
            IMRWeb.SearchService.GetSimpleSearchResultCountRequest inValue = new IMRWeb.SearchService.GetSimpleSearchResultCountRequest();
            inValue.Body = new IMRWeb.SearchService.GetSimpleSearchResultCountRequestBody();
            inValue.Body.any = any;
            inValue.Body.searchString = searchString;
            return ((IMRWeb.SearchService.SearchServiceSoap)(this)).GetSimpleSearchResultCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMRWeb.SearchService.GetSimpleSearchResultsResponse IMRWeb.SearchService.SearchServiceSoap.GetSimpleSearchResults(IMRWeb.SearchService.GetSimpleSearchResultsRequest request) {
            return base.Channel.GetSimpleSearchResults(request);
        }
        
        public string GetSimpleSearchResults(bool any, string searchString, int current, int pageSize) {
            IMRWeb.SearchService.GetSimpleSearchResultsRequest inValue = new IMRWeb.SearchService.GetSimpleSearchResultsRequest();
            inValue.Body = new IMRWeb.SearchService.GetSimpleSearchResultsRequestBody();
            inValue.Body.any = any;
            inValue.Body.searchString = searchString;
            inValue.Body.current = current;
            inValue.Body.pageSize = pageSize;
            IMRWeb.SearchService.GetSimpleSearchResultsResponse retVal = ((IMRWeb.SearchService.SearchServiceSoap)(this)).GetSimpleSearchResults(inValue);
            return retVal.Body.GetSimpleSearchResultsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMRWeb.SearchService.GetSimpleSearchResultsResponse> IMRWeb.SearchService.SearchServiceSoap.GetSimpleSearchResultsAsync(IMRWeb.SearchService.GetSimpleSearchResultsRequest request) {
            return base.Channel.GetSimpleSearchResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMRWeb.SearchService.GetSimpleSearchResultsResponse> GetSimpleSearchResultsAsync(bool any, string searchString, int current, int pageSize) {
            IMRWeb.SearchService.GetSimpleSearchResultsRequest inValue = new IMRWeb.SearchService.GetSimpleSearchResultsRequest();
            inValue.Body = new IMRWeb.SearchService.GetSimpleSearchResultsRequestBody();
            inValue.Body.any = any;
            inValue.Body.searchString = searchString;
            inValue.Body.current = current;
            inValue.Body.pageSize = pageSize;
            return ((IMRWeb.SearchService.SearchServiceSoap)(this)).GetSimpleSearchResultsAsync(inValue);
        }
    }
}
